"""empty message

Revision ID: 4b38cee8ac3
Revises: 3a63f28e1d72
Create Date: 2014-08-15 22:19:52.861234

"""

# revision identifiers, used by Alembic.
revision = '4b38cee8ac3'
down_revision = '3a63f28e1d72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'article', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column(u'article', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column(u'article', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'article', 'date_created')
    op.drop_column(u'article', 'category')
    op.drop_column(u'article', 'author')
    op.drop_table('comment')
    ### end Alembic commands ###
